# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 21:03
from __future__ import unicode_literals

from django.db import migrations, models

# Create a unique index in the backend to implement case-insensitive uniqueness
# of Node names. Idea from: https://stackoverflow.com/questions/7773341/case-insensitive-unique-model-fields-in-django
# Documentation on RunSQL method: http://django.readthedocs.io/en/1.11.x/ref/migration-operations.html#django.db.migrations.operations.RunSQL
class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_auto_20171107_2103'),
    ]

    operations = [
        migrations.RunSQL("CREATE UNIQUE INDEX node_name_index ON policies_node(lower(name));"),
    ]

