# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_create_functional_unique_index_for_node_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='node',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Please select publisher of journal, imprint or conference', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='policies.Node'),
        ),
    ]
