# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0004_auto_20171205_1536'),
        ('policies', '0004_auto_20171205_1415'),
    ]

    operations = [
    ]
