# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0005_merge_20171205_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='vetted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='node',
            name='vetted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
