# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0006_auto_20171205_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldpolicy',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goldpolicy',
            name='vetted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='goldpolicy',
            name='vetted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='greenpolicy',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='greenpolicy',
            name='vetted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='greenpolicy',
            name='vetted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oastatus',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oastatus',
            name='vetted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='oastatus',
            name='vetted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='retrospectiveoapolicy',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='retrospectiveoapolicy',
            name='vetted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='retrospectiveoapolicy',
            name='vetted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
