# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0007_auto_20171206_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='deletion_request',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='note',
            name='goldpolicy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent_gold_policy', to='policies.GoldPolicy'),
        ),
        migrations.AlterField(
            model_name='note',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='policies.Node'),
        ),
    ]
