# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0008_auto_20171218_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldpolicy',
            name='superseded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goldpolicy',
            name='superseded_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='goldpolicy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_gold_policy', to='policies.GoldPolicy'),
        ),
        migrations.AlterField(
            model_name='note',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='policies.Node'),
        ),
    ]
