# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0009_auto_20171221_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenpolicy',
            name='superseded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='greenpolicy',
            name='superseded_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='greenpolicy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_green_policy', to='policies.GreenPolicy'),
        ),
        migrations.AddField(
            model_name='note',
            name='oastatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_oa_status', to='policies.OaStatus'),
        ),
        migrations.AddField(
            model_name='note',
            name='retrospective_oa_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_retrospective_policy', to='policies.RetrospectiveOaPolicy'),
        ),
        migrations.AddField(
            model_name='oastatus',
            name='superseded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='oastatus',
            name='superseded_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='retrospectiveoapolicy',
            name='superseded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='retrospectiveoapolicy',
            name='superseded_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
