# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0010_auto_20171221_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goldpolicy',
            options={'ordering': ['superseded', '-vetted', '-updated'], 'verbose_name_plural': 'Gold policies'},
        ),
        migrations.AlterField(
            model_name='goldpolicy',
            name='last_checked',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goldpolicy',
            name='vetted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='greenpolicy',
            name='last_checked',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='greenpolicy',
            name='vetted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='vetted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oastatus',
            name='last_checked',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oastatus',
            name='vetted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='retrospectiveoapolicy',
            name='last_checked',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='retrospectiveoapolicy',
            name='vetted_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
