# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 11:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0011_auto_20171221_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='eissn',
            field=models.CharField(blank=True, help_text='Please use the format: <em>0000-0000</em>.', max_length=10, null=True, validators=[django.core.validators.RegexValidator('[0-9]{4,4}-[0-9]{4,4}', 'Please enter a issn in the format 0000-0000')], verbose_name='e-issn'),
        ),
    ]
