# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0015_auto_20171227_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenpolicy',
            name='version_green_licence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='policies.Licence'),
        ),
    ]
