# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0016_auto_20180102_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licence',
            name='node',
        ),
    ]
