# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0017_remove_licence_node'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oastatus',
            options={'permissions': (('can_confirm_delete', 'Confirm policy deletion'),), 'verbose_name_plural': 'Oa status'},
        ),
    ]
