# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0018_auto_20180104_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oastatus',
            options={'verbose_name_plural': 'Oa status'},
        ),
        migrations.RemoveField(
            model_name='goldpolicy',
            name='note',
        ),
        migrations.AddField(
            model_name='goldpolicy',
            name='verbatim',
            field=models.TextField(blank=True, help_text='Please copy and paste here the paragraph(s) from source stating this gold policy', null=True),
        ),
        migrations.AddField(
            model_name='greenpolicy',
            name='verbatim',
            field=models.TextField(blank=True, help_text='Please copy and paste here the paragraph(s) from source stating this green policy', null=True),
        ),
        migrations.AddField(
            model_name='oastatus',
            name='verbatim',
            field=models.TextField(blank=True, help_text='Please copy and paste here the paragraph(s) from source containing the OA status statement', null=True),
        ),
    ]
