# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-12 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0019_auto_20180104_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldpolicy',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gold_policies', to='policies.Node'),
        ),
        migrations.AlterField(
            model_name='greenpolicy',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='green_policies', to='policies.Node'),
        ),
        migrations.AlterField(
            model_name='greenpolicy',
            name='version_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='oastatus',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oa_stata', to='policies.Node'),
        ),
        migrations.AlterField(
            model_name='version',
            name='short_name',
            field=models.CharField(max_length=30),
        ),
    ]
