# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-03 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0024_auto_20180314_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='oastatus',
            name='problematic',
            field=models.BooleanField(default=False, help_text='Use this field to mark ambiguous/unclear policies requiring discussion/revision'),
        ),
    ]
