# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-03 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0025_oastatus_problematic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='policies.Source'),
        ),
    ]
