# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-21 23:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0030_auto_20180817_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='policies.Source'),
        ),
    ]
