# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-03 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0031_note_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epmc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participation_level', models.CharField(choices=[('FULL', 'Full'), ('NIH', 'NIH Portfolio'), ('NONE', 'No EPMC participation')], max_length=10)),
                ('embargo_months', models.IntegerField(blank=True, null=True)),
                ('open_licence', models.CharField(choices=[('ALL', 'All'), ('SOME', 'Some'), ('NO', 'No')], max_length=10)),
                ('deposit_status', models.CharField(choices=[('NO_NEW', 'No new content'), ('PREDECESSOR', 'Predecessor'), ('NOW_SELECT', 'Now select')], max_length=10)),
                ('vetted', models.BooleanField(default=True)),
                ('vetted_date', models.DateField(blank=True, null=True)),
                ('last_checked', models.DateField(blank=True, null=True)),
                ('superseded', models.BooleanField(default=False)),
                ('superseded_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='responsibility',
            options={'ordering': ('name',), 'verbose_name_plural': 'Responsibilities'},
        ),
        migrations.RemoveField(
            model_name='greenpolicy',
            name='europe_pmc_deposit',
        ),
        migrations.AddField(
            model_name='node',
            name='epmc_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
