# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-04 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0032_auto_20180904_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epmc',
            name='deposit_status',
            field=models.CharField(blank=True, choices=[('NO_NEW', 'No new content'), ('PREDECESSOR', 'Predecessor'), ('NOW_SELECT', 'Now select')], max_length=10, null=True),
        ),
    ]
