# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-04 00:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0034_epmc_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='epmc',
            name='source',
            field=models.ForeignKey(default='13', on_delete=django.db.models.deletion.PROTECT, to='policies.Source'),
            preserve_default=False,
        ),
    ]
