# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-04 00:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0035_epmc_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('applies_to', models.CharField(choices=[('AUTHORS', 'Authors'), ('INSTITUTIONS', 'Institutions')], max_length=20)),
                ('type', models.CharField(choices=[('NESLI VOUCHERS', 'NESLi vouchers'), ('OUP PREPAYMENT', 'OUP prepayment account'), ('SOCIETY DISCOUNT', 'Society membership discount'), ('SPRINGER COMPACT', 'Springer Compact'), ('WILEY DASHBOARD', 'Wiley Open Access Account'), ('MEMBER', 'Member'), ('OTHER', 'Other'), ('PREPAYMENT', 'Pre-payment account'), ('SUBSCRIBER', 'Subscriber')], max_length=20)),
                ('discount_currency', models.CharField(blank=True, choices=[('GBP', 'GBP - British Pound (£)'), ('EUR', 'EUR - Euro (€)'), ('USD', 'USD - United States Dollar ($)'), ('CHF', 'CHF - Swiss Franc (SFr.)'), ('AWG', 'AWG - Aruban Florin'), ('ALL', 'ALL - Lek'), ('AED', 'AED - UAE Dirham'), ('ARS', 'ARS - Argentine Peso'), ('AMD', 'AMD - Armenian Dram'), ('AUD', 'AUD - Australian Dollar'), ('BIF', 'BIF - Burundi Franc'), ('BDT', 'BDT - Taka'), ('BHD', 'BHD - Bahraini Dinar'), ('BRL', 'BRL - Brazilian Real'), ('BSD', 'BSD - Bahamian Dollar'), ('BZD', 'BZD - Belize Dollar'), ('BMD', 'BMD - Bermudian Dollar'), ('BOB', 'BOB - Boliviano'), ('BBD', 'BBD - Barbados Dollar'), ('BND', 'BND - Brunei Dollar'), ('BTN', 'BTN - Ngultrum'), ('BWP', 'BWP - Pula'), ('CAD', 'CAD - Canadian Dollar'), ('CLP', 'CLP - Chilean Peso'), ('CNY', 'CNY - Yuan Renminbi'), ('COP', 'COP - Colombian Peso'), ('KMF', 'KMF - Comoro Franc'), ('CVE', 'CVE - Cabo Verde Escudo'), ('CRC', 'CRC - Costa Rican Colon'), ('CUP', 'CUP - Cuban Peso'), ('KYD', 'KYD - Cayman Islands Dollar'), ('CZK', 'CZK - Czech Koruna'), ('DJF', 'DJF - Djibouti Franc'), ('DKK', 'DKK - Danish Krone'), ('DOP', 'DOP - Dominican Peso'), ('DZD', 'DZD - Algerian Dinar'), ('EGP', 'EGP - Egyptian Pound'), ('ERN', 'ERN - Nakfa'), ('FJD', 'FJD - Fiji Dollar'), ('FKP', 'FKP - Falkland Islands Pound'), ('GIP', 'GIP - Gibraltar Pound'), ('GNF', 'GNF - Guinea Franc'), ('GMD', 'GMD - Dalasi'), ('GTQ', 'GTQ - Quetzal'), ('GYD', 'GYD - Guyana Dollar'), ('HKD', 'HKD - Hong Kong Dollar'), ('HNL', 'HNL - Lempira'), ('HRK', 'HRK - Kuna'), ('HTG', 'HTG - Gourde'), ('HUF', 'HUF - Forint'), ('IDR', 'IDR - Rupiah'), ('INR', 'INR - Indian Rupee'), ('IRR', 'IRR - Iranian Rial'), ('IQD', 'IQD - Iraqi Dinar'), ('ISK', 'ISK - Iceland Krona'), ('ILS', 'ILS - New Israeli Sheqel'), ('JMD', 'JMD - Jamaican Dollar'), ('JOD', 'JOD - Jordanian Dinar'), ('JPY', 'JPY - Yen'), ('KZT', 'KZT - Tenge'), ('KES', 'KES - Kenyan Shilling'), ('KGS', 'KGS - Som'), ('KHR', 'KHR - Riel'), ('KRW', 'KRW - Won'), ('KWD', 'KWD - Kuwaiti Dinar'), ('LAK', 'LAK - Kip'), ('LBP', 'LBP - Lebanese Pound'), ('LRD', 'LRD - Liberian Dollar'), ('LYD', 'LYD - Libyan Dinar'), ('LKR', 'LKR - Sri Lanka Rupee'), ('LSL', 'LSL - Loti'), ('MOP', 'MOP - Pataca'), ('MAD', 'MAD - Moroccan Dirham'), ('MDL', 'MDL - Moldovan Leu'), ('MVR', 'MVR - Rufiyaa'), ('MXN', 'MXN - Mexican Peso'), ('MKD', 'MKD - Denar'), ('MMK', 'MMK - Kyat'), ('MNT', 'MNT - Tugrik'), ('MRO', 'MRO - Ouguiya'), ('MUR', 'MUR - Mauritius Rupee'), ('MWK', 'MWK - Malawi Kwacha'), ('MYR', 'MYR - Malaysian Ringgit'), ('NAD', 'NAD - Namibia Dollar'), ('NGN', 'NGN - Naira'), ('NIO', 'NIO - Cordoba Oro'), ('NOK', 'NOK - Norwegian Krone'), ('NPR', 'NPR - Nepalese Rupee'), ('NZD', 'NZD - New Zealand Dollar'), ('OMR', 'OMR - Rial Omani'), ('PKR', 'PKR - Pakistan Rupee'), ('PLN', 'PLN - Polish złoty'), ('PEN', 'PEN - Sol'), ('PHP', 'PHP - Philippine Peso'), ('PGK', 'PGK - Kina'), ('KPW', 'KPW - North Korean Won'), ('PYG', 'PYG - Guarani'), ('QAR', 'QAR - Qatari Rial'), ('RON', 'RON - Romanian Leu'), ('RSD', 'RSD - Serbian dinar'), ('RUB', 'RUB - Russian Ruble'), ('RWF', 'RWF - Rwanda Franc'), ('SAR', 'SAR - Saudi Riyal'), ('SGD', 'SGD - Singapore Dollar'), ('SHP', 'SHP - Saint Helena Pound'), ('SBD', 'SBD - Solomon Islands Dollar'), ('SLL', 'SLL - Leone'), ('SVC', 'SVC - El Salvador Colon'), ('SOS', 'SOS - Somali Shilling'), ('SSP', 'SSP - South Sudanese Pound'), ('STD', 'STD - Dobra'), ('SEK', 'SEK - Swedish Krona'), ('SZL', 'SZL - Lilangeni'), ('SCR', 'SCR - Seychelles Rupee'), ('SYP', 'SYP - Syrian Pound'), ('THB', 'THB - Baht'), ('TOP', 'TOP - Pa’anga'), ('TTD', 'TTD - Trinidad and Tobago Dollar'), ('TND', 'TND - Tunisian Dinar'), ('TRY', 'TRY - Turkish Lira'), ('TWD', 'TWD - Taiwan New Dollar'), ('TZS', 'TZS - Tanzanian Shilling'), ('UAH', 'UAH - Hryvnia'), ('UGX', 'UGX - Uganda Shilling'), ('UYU', 'UYU - Peso Uruguayo'), ('UZS', 'UZS - Uzbekistan Sum'), ('VEF', 'VEF - Venezuelan Bolívar'), ('VND', 'VND - Dong'), ('VUV', 'VUV - Vatu'), ('XAF', 'XAF - Central African CFA Franc'), ('WST', 'WST - Tala'), ('ZAR', 'ZAR - Rand')], max_length=10, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('vetted', models.BooleanField(default=True)),
                ('vetted_date', models.DateField(blank=True, null=True)),
                ('last_checked', models.DateField(blank=True, null=True)),
                ('superseded', models.BooleanField(default=False)),
                ('superseded_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='policies.Node')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='policies.Source')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='nodedeal',
            name='node',
        ),
        migrations.RemoveField(
            model_name='nodedeal',
            name='source',
        ),
        migrations.DeleteModel(
            name='NodeDeal',
        ),
    ]
