# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-06 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0036_auto_20180904_0148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='contact',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='policies.Node'),
        ),
        migrations.AddField(
            model_name='greenpolicy',
            name='output',
            field=models.ManyToManyField(help_text='Please select all output types this policy applies to.', to='policies.Output', verbose_name='outputs covered by green policy'),
        ),
    ]
