# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-05 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0037_auto_20180907_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greenpolicy',
            name='output',
        ),
        migrations.DeleteModel(
            name='Output',
        ),
    ]
