# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-13 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import policies.models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0038_auto_20181005_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(max_length=300, unique=True, validators=[policies.models.node_name_validator]),
        ),
        migrations.AlterField(
            model_name='node',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Please select publisher of journal, imprint or conference', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='policies.Node', verbose_name='Publisher'),
        ),
        migrations.AlterField(
            model_name='note',
            name='goldpolicy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gold_policy_notes', to='policies.GoldPolicy'),
        ),
        migrations.AlterField(
            model_name='note',
            name='greenpolicy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='green_policy_notes', to='policies.GreenPolicy'),
        ),
        migrations.AlterField(
            model_name='note',
            name='oastatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oa_status_notes', to='policies.OaStatus'),
        ),
        migrations.AlterField(
            model_name='note',
            name='retrospective_oa_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retrospective_policy_notes', to='policies.RetrospectiveOaPolicy'),
        ),
        migrations.AlterField(
            model_name='note',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_notes', to='policies.Source'),
        ),
    ]
